Repository vuejs/docs, pull requests merged in 2020-09, with the labels that each got.

#312 docs: added video explanation links for Vue 3
  src/guide/composition-api-introduction.md
  src/guide/composition-api-lifecycle-hooks.md
  src/guide/reactivity.md
  src/guide/teleport.md
Labels: release-candidate

#496 docs: update menu and migration guides
  src/.vuepress/config.js
  src/guide/migration/introduction.md
  src/guide/migration/v-bind.md
  src/guide/migration/v-if-v-for.md
  src/guide/migration/watch.md
Labels: review-alert-box

#510 docs: add redirect for new users
  src/guide/migration/introduction.md
Labels: review-alert-box

#507 Resolve props template usage composition api
  src/guide/composition-api-setup.md
Labels: awaiting-feedback
