Repository vuejs/docs, pull requests merged in 2020-08, with the labels that each got.

#355 Reword Vue instance/application parameters mentions
  src/api/application-api.md
  src/api/application-config.md
  src/api/directives.md
  src/api/instance-methods.md
  src/api/instance-properties.md
  src/api/options-assets.md
  src/api/options-data.md
  src/api/options-dom.md
  src/api/options-lifecycle-hooks.md
  src/guide/change-detection.md
  src/guide/class-and-style.md
  src/guide/component-basics.md
  src/guide/component-provide-inject.md
  src/guide/component-registration.md
  src/guide/composition-api-setup.md
  src/guide/computed.md
  src/guide/events.md
  src/guide/forms.md
  src/guide/instance.md
  src/guide/introduction.md
  src/guide/migration/events-api.md
  src/guide/migration/global-api-treeshaking.md
  src/guide/migration/global-api.md
  src/guide/mixins.md
  src/guide/plugins.md
  src/guide/reactivity.md
  src/guide/render-function.md
  src/guide/routing.md
  src/guide/state-management.md
  src/guide/template-syntax.md
  src/guide/transitions-state.md
Labels: enhancement, review-alert-box

#372 Fixed Simple State management section to use reactive
  src/guide/state-management.md
Labels: enhancement

#370 Added `outerHTML` -> `innerHTML` el change to docs
  assets/diagrams.sketch
  src/.vuepress/public/images/lifecycle.png
  src/guide/migration/introduction.md
Labels: enhancement

#181 feature (#169): add migration badges
  src/.vuepress/components/MigrationBadges.vue
  src/.vuepress/theme/styles/index.styl
  src/guide/migration/async-components.md
  src/guide/migration/attribute-coercion.md
  src/guide/migration/custom-directives.md
  src/guide/migration/custom-elements-interop.md
  src/guide/migration/data-option.md
  src/guide/migration/events-api.md
  src/guide/migration/filters.md
  src/guide/migration/fragments.md
  src/guide/migration/functional-components.md
  src/guide/migration/global-api-treeshaking.md
  src/guide/migration/global-api.md
  src/guide/migration/inline-template-attribute.md
  src/guide/migration/keycode-modifiers.md
  src/guide/migration/render-function-api.md
  src/guide/migration/slots-unification.md
  src/guide/migration/v-model.md
Labels: vue-3-migration-guide

#385 Add Vue Mastery Introduction to Vue 3 video
  src/guide/migration/introduction.md
Labels: release-candidate

#396 docs (#391): update provide inject in composition api with enhanced reactivity
  src/guide/composition-api-provide-inject.md
Labels: review-alert-box

#397 feat: migrate examples
  src/.vuepress/config.js
  src/examples/commits.md
  src/examples/elastic-header.md
  src/examples/grid-component.md
  src/examples/markdown.md
  src/examples/modal.md
  src/examples/select2.md
  src/examples/svg.md
  src/examples/todomvc.md
  src/examples/tree-view.md
Labels: content-migration

#413 docs (#26): migrate cookbook
  src/.vuepress/config.js
  src/.vuepress/theme/global-components/Badge.vue
  src/cookbook/editable-svg-icons.md
  src/cookbook/index.md
Labels: review-alert-box
