Repository vuejs/docs, pull requests merged in 2020-07, with the labels that each got.

#235 Update plugins section to guide style with example
  src/guide/plugins.md
Labels: enhancement

#252 Add an explanation for Vue builds
  src/guide/installation.md
Labels: enhancement

#289 Update computed properties example
  src/guide/computed.md
Labels: enhancement

#330 Reword preference of Vue Testing Library over Vue Test Utils
  src/guide/testing.md
Labels: enhancement

#340 Move non-prop attributes to a separate section
  src/.vuepress/config.js
  src/guide/component-attrs.md
  src/guide/component-basics.md
  src/guide/component-props.md
Labels: enhancement

#339 TypeScript section
  src/.vuepress/config.js
  src/guide/typescript-support.md
Labels: content-migration, enhancement

#107 [WIP] tag PRs using alert blocks
  .github/workflows/pr.yaml
  scripts/tag-alert-blocks.js
Labels: Uses alert blocks

#343 Replaced first example in Introduction
  src/.vuepress/components/FirstExample.vue
  src/guide/introduction.md
Labels: discussion, enhancement
