Repository vuejs/docs, pull requests merged in 2024-09, with the labels that each got.

#2798 Vuejsde conf banner september 16 22 2024
  .vitepress/inlined-scripts/restorePreference.js
  .vitepress/theme/components/Banner.vue
  .vitepress/theme/index.ts
  src/public/vuejsde-conf/vuejsdeconf_banner_large.png
  src/public/vuejsde-conf/vuejsdeconf_banner_large_2x.png
  src/public/vuejsde-conf/vuejsdeconf_banner_medium.png
  src/public/vuejsde-conf/vuejsdeconf_banner_medium_2x.png
  src/public/vuejsde-conf/vuejsdeconf_banner_small.png
  src/public/vuejsde-conf/vuejsdeconf_banner_small_2x.png
  src/public/vuejsde-conf/vuejsdeconf_banner_smallest.png
  src/public/vuejsde-conf/vuejsdeconf_banner_smallest_2x.png
Labels: core-team

#2993 docs (#2874): update quick start instructions for yarn v1
  src/guide/quick-start.md
Labels: content, state: review

#2994 docs (#2194): fix issue with autofocus on custom directives page
  src/guide/reusability/custom-directives.md
Labels: content, state: review, bug

#2985 Add developers pages, Proxify as a partner
  .gitignore
  .vitepress/config.ts
  .vitepress/theme/components/CallToActionSection.vue
  .vitepress/theme/components/CardList.vue
  .vitepress/theme/components/PageHero.vue
  .vitepress/theme/components/PageShowcaseListLayout.vue
  package.json
  pnpm-lock.yaml
  src/developers/[developerSlug].md
  src/developers/[developerSlug].paths.ts
  src/developers/components/DeveloperCard.vue
  src/developers/components/DeveloperCompensations.vue
  src/developers/components/DeveloperEducation.vue
  src/developers/components/DeveloperExperiences.vue
  src/developers/components/DeveloperHero.vue
  src/developers/components/DeveloperImage.vue
  src/developers/components/DeveloperJoin.vue
  src/developers/components/DeveloperLanding.vue
  src/developers/components/DeveloperPage.vue
  src/developers/components/DeveloperPageFooter.vue
  src/developers/components/DeveloperProficiencies.vue
  src/developers/components/DeveloperProfileDiagram.vue
  src/developers/components/type.ts
  src/developers/components/utils.ts
  src/developers/developers.json
  src/developers/index.md
  src/developers/partnerConfig.js
  src/partners/components/PartnerAll.vue
  src/partners/components/PartnerHero.vue
  src/partners/components/PartnerJoin.vue
  src/partners/components/PartnerLanding.vue
  src/partners/components/PartnerList.vue
  src/partners/components/PartnerPage.vue
  src/partners/components/type.ts
  src/partners/index.md
  src/partners/partners.json
  src/public/images/developers/1020-profile.svg
  src/public/images/developers/1020-score.svg
  src/public/images/developers/1346-profile.svg
  src/public/images/developers/1346-score.svg
  src/public/images/developers/2030-profile.svg
  src/public/images/developers/2030-score.svg
  src/public/images/developers/2535-profile.svg
  src/public/images/developers/2535-score.svg
  src/public/images/developers/3021-profile.svg
  src/public/images/developers/3021-score.svg
  src/public/images/developers/3709-profile.svg
  src/public/images/developers/3709-score.svg
  src/public/images/developers/4290-profile.svg
  src/public/images/developers/4290-score.svg
  src/public/images/developers/5022-profile.svg
  src/public/images/developers/5022-score.svg
  src/public/images/developers/5328-profile.svg
  src/public/images/developers/5328-score.svg
  src/public/images/developers/5697-profile.svg
  src/public/images/developers/5697-score.svg
  src/public/images/partners/proxify-dark.svg
  src/public/images/partners/proxify-hero.jpg
  src/public/images/partners/proxify.svg
Labels: core-team
